### ISSUE TITLE
Planos de assinaturas

### ISSUE THREAD

**Issue by rafamrquess** [mrayone/hotmart-webhook-create-member#3]
Olá, sugestão de atualização ao plugin. Incluir a opção de em caso de assinaturas, ele não gerar um novo acesso ao usuário. Pois como os planos são recorrentes, a cada pagamento a base atual está gerando um novo acesso e enviando. Grato!

**Comment by rafamrquess** [comment]
Vou incluir um detalhe. Quando o boleto é gerado, ele ja ta cadastrando o usuário. Mas o ideal é após o pagamento na maioria dos casos.

**Comment by mrayone** [comment]
Certo, pelo o que vi na api do Hotmart ele envia a opção subscription_status via chamada webhook, ou seja, da para mapear por esta função. No caso do boleto, a chamada vem com status approved? Então o correto seria criar a conta quando a compra está completed, vou verificar.

**Comment by rafamrquess** [comment]
Isso, correto. Ai vem aquele caso, o boleto é enviado mensalmente. Não sei se no envio de um novo aprroved, ele irá gerar uma nova conta / senha. Uma dúvida, durante o cadastro, seria possível a pessoa escolher uma senha em vez do WP mandar uma aleatória?

**Comment by mrayone** [comment]
Eu acho pouco seguro, visto que robôs podem ser desenvolvidos para gerar logins, o plugin é código aberto e qualquer pessoa pode baixa-lo e estuda-lo, então tornaria o site vulnerável.

**Comment by novaskideveloper** [comment]
Olá @mrayone, tudo bem?

Estou auxiliando o Rafael e verifiquei as seguintes linhas de código:
![image](https://user-images.githubusercontent.com/15522629/83977319-21195f00-a8d6-11ea-8975-522c30f47c72.png)

Nessa imagem, você já faz uma verificação se o usuário existe na base. Mas mesmo que ele exista, você altera a senha dele. Gostaria de saber se eu fizer um commit alterando essa classe para que quando o E-mail exista, ele não troque a senha e não envie um E-mail você poderia aprovar e incorporar no plugin?

Obrigado

**Comment by novaskideveloper** [comment]
@mrayone outra coisa, sobre a questão dos status. Eu achei esse trecho de código:

![image](https://user-images.githubusercontent.com/15522629/83977404-b0bf0d80-a8d6-11ea-8c42-57f2bb4e4c61.png)

Nele, você está usando o status approved ao inves do status completed, eu poderia fazer um commit e alterar para o status completed?

Obrigado

**Comment by mrayone** [comment]
Boa noite tudo e com você? Pode fazer o PR que eu verifico o código e aceito!

Com relação a senha não me recordo ao certo o do porque eu a alterava, mas
ocorreu uma necessidade específica que eu achei que cabia.

Att,
Maycon.

Em dom., 7 de jun. de 2020 às 15:51, novaskideveloper <
notifications@github.com> escreveu:

**Comment by ofmarconi** [comment]
Olá @mrayone Você tem projetos de manter esse plugin? Talvez monetizar ele...

Só pra saber, estou prestes a montar um negocio e queria ter uma perspectiva sobre esse projeto seu, ainda não testei...

Minha pergunta também é sobre esse Issue, ele foi solucionado @novaskideveloper @rafamrquess ?

Abraço e parabéns a todos!

**Comment by mrayone** [comment]
Fora do escopo do plugin, estou fechando a issue. Caso desejem fazer plano de assinaturas, sugiro criar uma extensão ou add-ons.
