### ISSUE TITLE
Token disparado pelo hotmart diferente do fornecido na documentação da API.

### ISSUE THREAD

**Issue by Msantanna10** [mrayone/hotmart-webhook-create-member#4]
Olá encontrei este plugin e ele parece ser realmente bom e fazer justamente o que busco, coloquei meu token no campo, digitei o link na hotmart (...../wp-json/hothook/v1/users)

Mas no histórico ele retorna:
HTTP Status Code: | 502
Data: | 08/06/2020 21:52:06
Retentativas: | 1
Próxima retentativa: | 08/06/2020 22:07:06
**"TokenInválido!"**

Mas o token está correto! É o token gerado em: Ferramentas > WebHook > Documentação

O que estou deixando passar?

**Comment by mrayone** [comment]
Olá tudo bem? 
Não fiz ainda um review para as ultimas versões da api do Hotmart, porém acredito que sim. Se possível coloque a requisição de teste do hotmart aqui na issue. Outra detalhe, pode apagar o seu token ou qualquer informação sensível antes de postar aqui, para que então eu posso analisar com mais cuidado qual o possível problema.

Att.

**Comment by gabrieldamazio** [comment]
Aconteceu o mesmo comigo, fui utilizar e recebi o mesmo erro

HTTP Status Code: | 502
-- | --
Data: | 20/07/2020 00:00:30
Retentativas: | 1
Próxima retentativa: | 20/07/2020 00:15:30

"TokenInválido!"

**Comment by Msantanna10** [comment]
> 
> 
> Aconteceu o mesmo comigo, fui utilizar e recebi o mesmo erro
> HTTP Status Code: 	502
> Data: 	20/07/2020 00:00:30
> Retentativas: 	1
> Próxima retentativa: 	20/07/2020 00:15:30
> 
> "TokenInválido!"

Então, veja se não está cometendo o mesmo erro que eu, pois eu estava fazendo a proeza de tentar realizar os testes sem meu produto ter sido aprovado ainda rsrs.

Mas não testei depois porque a Hotmart anda de tiração, meu produto não está com eles.

Mas deixa seu relato se conseguir, que aí já ajuda os que forem usar, quem sabe mais pra frente eu não volte com a Hotmart também.

Valeu.

**Comment by gabrieldamazio** [comment]
> > Aconteceu o mesmo comigo, fui utilizar e recebi o mesmo erro
> > HTTP Status Code: 	502
> > Data: 	20/07/2020 00:00:30
> > Retentativas: 	1
> > Próxima retentativa: 	20/07/2020 00:15:30
> > "TokenInválido!"
> 
> Então, veja se não está cometendo o mesmo erro que eu, pois eu estava fazendo a proeza de tentar realizar os testes sem meu produto ter sido aprovado ainda rsrs.
> 
> Mas não testei depois porque a Hotmart anda de tiração, meu produto não está com eles.
> 
> Mas deixa seu relato se conseguir, que aí já ajuda os que forem usar, quem sabe mais pra frente eu não volte com a Hotmart também.
> 
> Valeu.

Infelizmente não é o caso, meu produto tá aprovado sim.

**Comment by mrayone** [comment]
Vocês verificaram a requisição de testes que possui na aba de WebHooks do hotmart? Essa mensagem de "token inválido" só ocorre quando o token fornecido no cadastro do plugin está diferente do token enviado pelo hotmart.

**Comment by gabrieldamazio** [comment]
`Documentação

Nossa API de POSTS automatiza o controle dos seus produtos e otimiza a entrega para o cliente, além de poder ser integrada a qualquer sistema. Para criar esta integração, é necessário conhecimento em programação.

O token de verificação e segurança que enviamos pra você em todas as notificações é **(USEI ESSE TOKEN)**

Todos os parâmetros são enviados para o Produtor.

O webhook da Hotmart espera que sua aplicação responda uma mensagem com no máximo 5000 caracteres.`

Daí fiz o teste e ele já manda o token invalido.

**Comment by mrayone** [comment]
> `Documentação
> 
> Nossa API de POSTS automatiza o controle dos seus produtos e otimiza a entrega para o cliente, além de poder ser integrada a qualquer sistema. Para criar esta integração, é necessário conhecimento em programação.
> 
> O token de verificação e segurança que enviamos pra você em todas as notificações é **(USEI ESSE TOKEN)**
> 
> Todos os parâmetros são enviados para o Produtor.
> 
> O webhook da Hotmart espera que sua aplicação responda uma mensagem com no máximo 5000 caracteres.`
> 
> Daí fiz o teste e ele já manda o token invalido.

Certo, vou configurar o ambiente hoje e verificar se ainda está funcional.

**Comment by patricksponte** [comment]
Oi, Pessoal. Boa tarde!

Estava tendo o mesmo problema que o @Msantanna10 ("TokenInválido!").
Acontece que o Token informado pelo Hotmart na aba Documentação, não corresponde ao Token que devemos utilizar no plugin. 

Para funcionar, eu peguei o valor do **hottok** no cabeçalho do evento de teste gerado pelo Hotmart e inseri no plugin.
Abra o seu hotmart e vá em Ferramentas -> Webhook -> Histórico e clique em Histórico de "Responses" (lupa com +), copie o valor **hottok** e faça um teste.

Depois de fazer isso, o HTTP Status Code mudou para 200 e o plugin passou a funcionar.

Também diz um teste pelo PostMan e funcionou perfeitamente. 

@mrayone parabéns cara, extremamente útil o seu plugin. 

Abs

**Comment by gabrieldamazio** [comment]
> Oi, Pessoal. Boa tarde!
> 
> Estava tendo o mesmo problema que o @Msantanna10 ("TokenInválido!").
> Acontece que o Token informado pelo Hotmart na aba Documentação, não corresponde ao Token que devemos utilizar no plugin.
> 
> Para funcionar, eu peguei o valor do **hottok** no cabeçalho do evento de teste gerado pelo Hotmart e inseri no plugin.
> Abra o seu hotmart e vá em Ferramentas -> Webhook -> Histórico e clique em Histórico de "Responses" (lupa com +), copie o valor **hottok** e faça um teste.
> 
> Depois de fazer isso, o HTTP Status Code mudou para 200 e o plugin passou a funcionar.
> 
> Também diz um teste pelo PostMan e funcionou perfeitamente.
> 
> @mrayone parabéns cara, extremamente útil o seu plugin.
> 
> Abs

No meu caso só fez mudar o error:


HTTP Status Code: | 502
-- | --
Data: | 21/07/2020 14:04:54
Retentativas: | 1
Próxima retentativa: | 21/07/2020 14:19:54

"Errodeconfiguraçãodoplugin!"

**Comment by gabrieldamazio** [comment]
> > Oi, Pessoal. Boa tarde!
> > Estava tendo o mesmo problema que o @Msantanna10 ("TokenInválido!").
> > Acontece que o Token informado pelo Hotmart na aba Documentação, não corresponde ao Token que devemos utilizar no plugin.
> > Para funcionar, eu peguei o valor do **hottok** no cabeçalho do evento de teste gerado pelo Hotmart e inseri no plugin.
> > Abra o seu hotmart e vá em Ferramentas -> Webhook -> Histórico e clique em Histórico de "Responses" (lupa com +), copie o valor **hottok** e faça um teste.
> > Depois de fazer isso, o HTTP Status Code mudou para 200 e o plugin passou a funcionar.
> > Também diz um teste pelo PostMan e funcionou perfeitamente.
> > @mrayone parabéns cara, extremamente útil o seu plugin.
> > Abs
> 
> No meu caso só fez mudar o error:
> HTTP Status Code: 	502
> Data: 	21/07/2020 14:04:54
> Retentativas: 	1
> Próxima retentativa: 	21/07/2020 14:19:54
> 
> "Errodeconfiguraçãodoplugin!"

Deixei apenas o reembolso e o de pagamento aprovado e deu certo, valeu todos vocês salvaram meu dia <3

**Comment by mrayone** [comment]
> Oi, Pessoal. Boa tarde!
> 
> Estava tendo o mesmo problema que o @Msantanna10 ("TokenInválido!").
> Acontece que o Token informado pelo Hotmart na aba Documentação, não corresponde ao Token que devemos utilizar no plugin.
> 
> Para funcionar, eu peguei o valor do **hottok** no cabeçalho do evento de teste gerado pelo Hotmart e inseri no plugin.
> Abra o seu hotmart e vá em Ferramentas -> Webhook -> Histórico e clique em Histórico de "Responses" (lupa com +), copie o valor **hottok** e faça um teste.
> 
> Depois de fazer isso, o HTTP Status Code mudou para 200 e o plugin passou a funcionar.
> 
> Também diz um teste pelo PostMan e funcionou perfeitamente.
> 
> @mrayone parabéns cara, extremamente útil o seu plugin.
> 
> Abs

Que bom que te ajudou!

Pretendo fazer umas melhorias na parte documental e estrutural do plugin. Espero contribuir mais para a comunidade!
Sendo assim se todos concordarem vou modificar o status da issue!

**Comment by mrdamaia** [comment]
Testei hoje e está funcionando certinho. Só vou precisar fazer algumas alterações quanto a nível de acesso dependendo do plano.
