### ISSUE TITLE
O plugin deixou de funcionar no hotmart :'(

### ISSUE THREAD

**Issue by gabrieldamazio** [mrayone/hotmart-webhook-create-member#5]
HTTP Status Code: | -1
-- | --
Data: | 19/10/2020 11:25:30
Retentativas: |  
Próxima retentativa: | 19/10/2020 11:40:30

**Comment by gabrieldamazio** [comment]
> HTTP Status Code: 	-1
> Data: 	19/10/2020 11:25:30
> Retentativas: 	 
> Próxima retentativa: 	19/10/2020 11:40:30

Além de deixar de funcionar, começou a sobrecarregar o servidor. Vi esse mesmo plugin para compra aqui: https://www.dropestore.com/downloads/hotmart-webhook-plugin-wordpress/

**Comment by gabrieldamazio** [comment]
Esse plugin não funciona com o TLS 1.3

**Comment by mrayone** [comment]
Olá, obrigado pela participação. Desculpe a demora.

Vamos resolver, pode me dar mais informações, com relação a consumo de memoria e qual tipo de web server você distribui o seu blog? (apache, nginx)

**Comment by mrayone** [comment]
Plugin funcionando corretamente.
